### ISSUE TITLE
Now starting

### ISSUE THREAD

**Issue by anshtyagi0** [Tomato6966/Music-Bot-with-Filters-#10]
 npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-04-10T14_48_25_027Z-debug.log
exit status 1

**Comment by HiroTechys** [comment]
Go to package.json and in:
  "scripts": {
  },
  
  Add 
    "start": "node index.js"
    
  So it may look like
    "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node index.js"
  },

**Comment by anshtyagi0** [comment]
ok let me try

**Comment by HiroTechys** [comment]
Sure take your time

**Comment by anshtyagi0** [comment]
ok it worked thanks
