### ISSUE TITLE
Error Console

### ISSUE THREAD

**Issue by pro225** [Tomato6966/Music-Bot-with-Filters-#2]
![image](https://user-images.githubusercontent.com/69795736/97843139-cb26d700-1d0e-11eb-96bb-0c3071ad6c1f.png)

**Comment by pro225** [comment]
![image](https://user-images.githubusercontent.com/69795736/97843462-599b5880-1d0f-11eb-835a-5ee96ceb8be1.png)

**Comment by Tomato6966** [comment]
Are u using the template or did you fork it?

**Comment by Tomato6966** [comment]
Update your node version to v12 this will fix it!
