### ISSUE TITLE
Bot join's then leaves when i do .play (song title)

### ISSUE THREAD

**Issue by Fireman057299** [Tomato6966/Music-Bot-with-Filters-#7]
When i try to tell the bot to .play song it just joins and leaves and I don't know why (is there a fix to this) it doesn't even show a error code ether which is weird. its shows the song i requested then once it leaves it says music queue ended.

**Comment by Tomato6966** [comment]
weird...

**Comment by Tomato6966** [comment]
can i see some screenshots?

**Comment by Fireman057299** [comment]
yea the thing is it doesn't source a code error when the bot leaves
